### ISSUE TITLE
about cifar tutor

### ISSUE THREAD

**Issue by Ariex** [Microsoft/caffe#46]
according to this tutor located at [https://github.com/Microsoft/caffe/blob/master/examples/cifar10/readme.md](https://github.com/Microsoft/caffe/blob/master/examples/cifar10/readme.md), i have successfully got all necessary executable files, download dataset, convert, etc.
But I ends with an error when I executing `build\x64\Release\caffe train --solver="X:/caffe/examples/cifar10/cifar10_quick_solver.prototxt"` from `X:\caffe\`, there are a lot outputs, and the last 3 lines are
`I0315 23:34:06.160449  7416 solver.cpp:338] Iteration 0, Testing net (#0)`
`F0315 23:34:06.171448  7416 pooling_layer.cu:212] Check failed: error == cudaSuccess (8 vs. 0)  invalid device function  `
`*** Check failure stack trace: ***`
I have tried with Release build and Debug build, both ends with same thing, one message box ask me if I want debug the error with nothing details.

Just wonder if anyone have made this working and may knew what this error means?

Thanks very much~

**Comment by mnidza** [comment]
Make sure that you're building for the correct CUDA architecture (check the `<CudaArchitecture>` macro in `<caffe_root>\windows\CommonSettings.props`).

**Comment by Ariex** [comment]
I am new to caffe thing, could you tell me more about how to make it correct?
I currently is use the default value `compute_35,sm_35;compute_52,sm_52`, as far as I can see the caffe compilation is fine, I can compile and get the executable in build folder

Thanks~

**Comment by sasagalic-MSFT** [comment]
@Ariex what GPU do you have? Reported error (8) suggests that either your GPU device does not support certain functionality or you have not compiled Caffe for appropriate architecture.
If it turns out that you cannot use your GPU you can always perform experiment on CPU.

**Comment by Ariex** [comment]
I am using NVidia GeForce GTX 660 Ti, quote an old adapter...

**Comment by Ariex** [comment]
i have found this post http://timdettmers.com/2014/08/14/which-gpu-for-deep-learning/, seems 660 or 660 Ti won't work, so sad....

thank you for your help @sasagalic-MSFT~

**Comment by Ariex** [comment]
OK, problem solved. Not sure if it necessary to rebuild when CommonSettings.props modified, but I did so..
then for the cifar, i also modified the `X:\caffe\examples\cifar10\cifar10_quick_solver.prototxt`, last line, change GPU to CPU.

Now it is running all correctly~ issue solved~

**Comment by mnidza** [comment]
Excellent, thanks for letting us know.
